// Generated by CoffeeScript 1.7.1
(function() {
  window.NS = {
    a: function() {
      return NS.b() + 2;
    },
    b: function() {
      return 4;
    }
  };

  window.someFunction = function(a, b) {
    return (2 * a + b) + "asdf";
  };

  window.init = function() {
    var a, b, inner;
    inner = function() {
      return 2 + 2;
    };
    console.log(ATest["static"]());
    console.log(b + inner());
    a = new ATest(42);
    console.log(a);
    console.log((b = a.doA()));
  };

  new ControlFlowDiagram();

}).call(this);
