// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = {};

  window.ATest = (function() {
    ATest["static"] = function() {
      NS.b();
      return 5;
    };

    function ATest(a) {
      if (a == null) {
        a = 2;
      }
      this.a = a;
      this.ar = [1, 2];
      this.doA();
      this["static"] = ATest["static"]();
    }

    ATest.prototype.doA = function(x) {
      return NS.a() || x || 2;
    };

    return ATest;

  })();

  window.App.BTest = (function() {
    function BTest() {
      this.b = 3;
      this.a = new ATest();
      this.ar = [true, false];
      this.mixed = [3, "a"];
      this.arrayOfA = [new ATest(), new ATest()];
      this.stringAr = ["asdf", "bsfd"];
    }

    BTest.prototype.__uml_init = function() {
      return {
        c: new CTest()
      };
    };

    BTest.prototype.doB = function(a, b, c) {
      var temp;
      temp = this.doB2();
      return new ATest(temp);
    };

    BTest.prototype.doB2 = function() {
      return 42;
    };

    return BTest;

  })();

  window.CTest = (function() {
    function CTest() {
      this.c = 3;
      this.a = new ATest();
      this.b = new App.BTest();
    }

    CTest.prototype.doC = function(a, b) {
      return 3;
    };

    return CTest;

  })();

  window.ASub = (function(_super) {
    __extends(ASub, _super);

    function ASub() {
      this.sub = 42;
      this.b = new App.BTest();
    }

    return ASub;

  })(ATest);

  window.App.ASubSub = (function(_super) {
    __extends(ASubSub, _super);

    function ASubSub() {
      this.subsub = 42;
      this.b = new App.BTest();
    }

    return ASubSub;

  })(ASub);

}).call(this);
